### ISSUE TITLE
New logo for Goldfish

### ISSUE THREAD

**Issue by reallinfo** [staticintlucas/Goldfish#1]
I wanted to contribute to Goldfish I designed a logo for Goldfish. If you like it, I'll send you all files.

![goldfish](https://user-images.githubusercontent.com/36298335/38147008-1d1a506a-3459-11e8-8e01-0af5c95e58eb.jpg)

**Comment by staticintlucas** [comment]
That is a pretty cool logo! I'm not sure how well it would look on the PCB, and I don't want to change it right now because I'm lazy.

But do feel free to add it (even just to the README if you're not confident with PCB design) and submit a PR
