### ISSUE TITLE
[Question] Changes

### ISSUE THREAD

**Issue by rickyosser** [staticintlucas/Goldfish#10]
Hi,

I'm interested in your design but would like to know how hard it would be to change the design to:
1,  include an onboard voltage regulator
2, remove the USB-connector and add soldering points for +5 and GND in in addition to the data-lines

I'm not an electrical engineer and this might be a bit out of my league to do by myself.

Thanks in advance,
Rickard

**Comment by staticintlucas** [comment]
If you have a little experience designing PCBs it shouldn't be too difficult to make those changes.

For the voltage regulator, you can have a look at the original Pro Micro schematic [here](http://cdn.sparkfun.com/datasheets/Dev/Arduino/Boards/Pro_Micro_v13b.pdf), which includes a voltage regulator. You don't even need to add additional soldering points for USB, there are already 2 through holes for the D+/- lines, GND can just be connected to a ground pin, and +5V to the RAW pin.

The biggest issue when designing the PCB was having enough room to fit everything in, but without the USB connector you should have plenty of room to fit the regulator.
