### ISSUE TITLE
prototypes / groupbuy?

### ISSUE THREAD

**Issue by fieldju** [staticintlucas/Goldfish#2]
I found this project via https://geekhack.org/index.php?topic=93571.0, while googling pro-micro with usb-c after breaking my usb port off and having to desolder and re-solder a replacement.

Any chance there will be a group buy or ability to acquire a prototype?

**Comment by brianweyer** [comment]
I'd also be interested in this.

**Comment by staticintlucas** [comment]
There are a bunch of other alternatives these days so I don't see much point in running a group buy, besides I don't really have the free time to run something like that right now.

The project is open source for a reason though, so if anyone else wants to roll with it feel free.
